name: CI - Build & Scan

on:
  push:
    branches: [main]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t nginx-app:latest .

      - name: Scan with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: nginx-app:latest
          format: table
          exit-code: 1
          severity: CRITICAL

      - name: Push to Docker Hub
        if: success()
        run: |
          echo "${{ secrets.HARBOR_PASSWORD }}" | docker login -u "${{ secrets.HARBOR_USER }}" --password-stdin
          docker tag nginx-app:latest tomtech16univ/nginx-app:latest
          docker push tomtech16univ/nginx-app:latest
